language: java
jdk:
  - oraclejdk8
branches:
  except:
    - master
script:
  - mvn verify
  - mvn org.jacoco:jacoco-maven-plugin:prepare-agent verify
  - mvn sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=iraticasi-github -Dsonar.login=$SONAR -Dsonar.projectKey=iraticasi_klondike